Add new PSC and committer members
thegooddocsproject/thegooddocsproject.github.io pull request #51
Opened 2020-09-15 12:36 UTC by camerons

Add who-we-are page which adds new committer and PSC members

Project Steering Committee:
* Morgan Craft
* Alyssa Rock

Committer:
* Lana Brindley
* Daniel Beck
* Viraji Ogodapola

2020-09-15 18:34 UTC, mgan59 requested changes
Happy to push up my changes with the `yaml` piece and handle the rebase. but was holding off if there were other changes from fellow members.

2020-09-15 18:34 UTC, mgan59 commented on who-are-we.md
> +
Need to include __frontmatter__ / `yaml` to any new topic-pages.  Otherwise, the `who-are-we.html` won't build for local dev-environments.

2020-09-15 18:34 UTC, mgan59 commented on who-are-we.md
> +
Tested the following `yaml` locally.

```yaml
---
layout: default
---
```

![good-docs-pr51-review](https://user-images.githubusercontent.com/89339/93250099-454fcc00-f760-11ea-997a-17bc99b0b065.gif)

2020-09-15 18:37 UTC, mgan59 commented
All the links work, content for new members looks correct. I'm a 👍    

`yaml` is required for the build to function, happy to push my changes up -- Or feel free to drop the `yaml` into your branch.

2020-09-16 00:36 UTC, camerons commented
Thanks for the reveiw @mgan59 . Yes, it would be great if you could add the front matter. I thought I had already done that, but seems I've tripped over myself in git.

2020-09-21 10:31 UTC, mgan59 approved these changes

2020-09-21 10:31 UTC, mgan59 commented
@camerons sorry for the delay here pushed up the `yaml`.  Should be all set now. 👍

2020-09-21 20:14 UTC, camerons commented
Merging now, based on fix and approval from @mgan59. Thanks Morgan.

2020-09-21 20:14 UTC, merged